services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks: [appnet]

  wildfly:
    build:
      context: wildfly
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: ${TZ}
      WF_MGMT_USER: ${WF_MGMT_USER}
      WF_MGMT_PASS: ${WF_MGMT_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DS_NAME: ${DS_NAME}
      JDBC_DRIVER_NAME: ${JDBC_DRIVER_NAME}
      DEBUG: "true"
      DEBUG_PORT: 5005
    ports:
      - "8080:8080"   # app
      - "9990:9990"   # console/admin
      - "5005:5005"   # debug
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments
    networks: [appnet]

networks:
  appnet:

volumes:
  pgdata:
